apiVersion: v1
kind: Secret
metadata:
  name: text-extraction-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData: 
  STORAGE_ACCESS_KEY: {{ .Values.storage.access_key }}
  STORAGE_ACCESS_SECRET: {{ .Values.storage.access_secret }}
  POSTGRES_USER: {{ .Values.postgresql.user }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password }}
  OPENSEARCH_USER: {{ .Values.opensearch.user }}
  OPENSEARCH_PASSWORD: {{ .Values.opensearch.password }}
